grafana:
  enabled: true

  securityContext:
    runAsNonRoot: true
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472

  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 472
    allowPrivilegeEscalation: false

promtail:
  enabled: true

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 10001
    fsGroup: 10001

loki:
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 10001
    fsGroup: 10001
