apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ledger-api-reader
  namespace: payments

rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ledger-api-reader-binding
  namespace: payments

subjects:
  - kind: ServiceAccount
    name: ledger-api
    namespace: payments

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ledger-api-reader
