---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgAyya2hfYfoYBDzQcETZ4zCdIsJvkhY3uvlOWM5XMa/X9tG+pH+AFhFIEUNT+nmi0ePRwKosiCkQGVdRnSQ9qJpTBzghsDM/KbpI6JyrOAjnXQjeHE+cWKhSVOdSqGtNTRZpoCYF4focPYob3SypawfEdb7BI1rw28G7dRoUT+s/cHNyJXPK9Ohvq7Gipe6EqO5xKda8uyET7BxqeuqXKQaJdrDdUvvOHZc5o0KJ3q5IwOos5t/YfCL/OHQ6ixPOFE/iKU5DLPIbMuQENSr1zEKBQRsNcNoDCXLO1kjPldJi62iILIGvnFaTanHUXk5JDD/Mz6DwnurCkp+fA1ZlKvuHj30cCDroq7OqXdLdHh1ymGXGUhjmOO2k/tP8d2CjaKxehADdchpVRNZAmscWHO3yp8FqSSwY7mPd8LZVsz8AWTYaQ5to0NrGmolRj0PY8EwEIvc+XxBER6bnF9U8VseUjR78HGLlYSfWo030JzZ66LpDPun+PQaNV4X8UCOdHCHuULJRhq/sq546g+t3RdCEdmaVXrZQUR2UzjrrUksYSrXqMiZDAdx413gyW1d/VPDPOHHw5GNtWDBI96q2LNKDVPtNn65bZdyCeG4xl1edomga+OIJJnOAHF8cDSmvdRvfGy7HWrrvvGewf6yRX0ya9mJmEQneK9rgBasZwuFkXHjd50QVW9xTiy8N+Q/thRCxYXKpjigB570dw==
    STRIPE_API_KEY: AgB2UiFWBKfgDCfSACVUGJknS7RCu1Mnb0aoGw1/awNxiHNVFnVbDw8TBcfiZLx22xXyXXumLTgzxM7iOorPL9eMYAFKT1xsv2Ot2tgMTP6z1DMv1f42+vn88sEd1tVmaO1Lbj8UO8XxzajDG+GZtOtczhQlZ5lvR6Oc9FfP3jZrLT1v9riTx0nhhKP1qtCpQic1G2mbH4WTvHKDch1YX8Ew0zn6cTjNeLVVhdC9naHJ8xcH2k45vCXhOeG2EbPTLRzIggo3+NX2qNCsLai+wxdrZX8zEW2n6AR9n507ixpTii2Wc8S1SFG/GRi+mXiJy+r9frztbQZhcSnSXX5+PVL1EhfQH/0sL3FGjX2Brw+2ZhHLtGNamGITTh+M8si8mfm3ohl1YLjUfZFqhmg+6ir/PcO/gGG+2yz7gzu3tXhTtbonlJUJwFixkHkR0zqYi/WYdopuksjV2GZWXr+LbxiE/MciA6PAY/UrT1yGRNrLNvAvNniZIBM7kCBd+vMfk7MVNq6BSTzUXbJxS0BjzlfYsP6qN3/odzMd4lH6aqzYk2rYi/xdcx3xtecF2m9fzRb0RrtuRWE0WV0soGTohukEZGtbyNJF6iDwfVD0Qg/Z/1yfOMU73u69454+DJb3MikaaCd4D2WxzOP+GSxUOPdaABP4MQp0Ow9R7wyWOz8LHomDCM1ScfdW+PXV3aE2RByA8XVWK7Z8nm4TO8sOJC0AIHIQ7mpuzuxSP40Hkw==
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
    type: Opaque
