---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgCokAvZWfJYjPy0PCe45cIh5OgzodLIU4RE64QgNWINYmyeexQjBvoT5AqfVbP50Wp6vpAqGc6/bP5bp2WajHqX5DzrnhGSuZRATu+w3xE9FI7x1Spicn/gq2vWnbu+1KP5rXcknyVsS6txAY9/a0RfDwILi0LAUE/DlT8owfdbg5+xRoVZkeHDA+pemZG351wfQkowH0DMOTh4ElfbxAOxaYk9jqlBuUQChpzG6xZItjOjqNQMMNjt34a8FYsce+zz768hMCRNoZ8ZzK6K4o0tQpQxVNHtN5Mcp+maPhF5M8uke4KSdn2uViJ0wQB1zultOy4m9xrKxy5nXtOg8UmrSxXa3h0zALQRJ2Rgt27KsF+M+Sq97HLMZK8KgYtqHsd8mnJUG8ww8FEmpkqIRfvFfx0YhnrL02dczOpFsQ7Rb9prLJHCVEcM84GDfTEsOmx0OchYBRqWKt5loel9pWc4ZGfkNj0VMwsWbs04oNF0L48kMrwTjHy76k9d9eA4b8ncXLox0DMgIv9V5SeuoQTmkc5c7jf3fO5omK4ELPKu8CbHuS83atLRdIe2HmURHHUCS0VDk8c9UkfmWu3lWnw5lOAw/7D1+1S6ZGS7S/K0/f6TDs3yqvlDIH8V6zqFTW3Po0qhvZN4aKCJh0hELOzXhYmc5mMffWOLDfVz2MAX5AhtzRpeaB96yHEhLkegbZUIjsIY3gWhlpk16g==
    STRIPE_API_KEY: AgA3t4HZZxsvzpT4WRmoCM/NweRq+7aIOWqhYucwTfdF8pFSGL+PZsB+tUh/jyKTamCP7J+FCIqY33K+eX0YJfn3Hp/3W9GbmGF+2j1JVmCpZZ61Rqcj+95R5v7y8ynQWlT7RGtVQK1bgS7CR6wlDWBuQWKYLD/oyQQmrCHeYGrppKz9Y+snYZ6WuyMfXhrSkrWcszJQVsyhMiUGWKdwH7wRfRX8WvQFsJolYydM74HXZ3j8uXQ+PTms3bOwePvi2YxscQZun6JZOcW624JOCu5qPvVBI/cHCriukpIiAWymvnByq19SSO4W+/IHemUF4BhWqwAF+6sGg7LjCl6cQTnYqYrnKni1qP+fV10Ssb3GbUiTir+yjfONqNOpE+EmbgUPv0d376RT1YC5hxLS2f1k/uLrF7FmLWfXL1v9XSa2DZU1Jx8tfRrDuaFkxwrQjUYZbWTzQZ+u6VGLyaYjvz8/bBsF3puD4/Cxns4nm0UQ7uFjy2jaBibM58abt1nS9lUrzcop+PR5DVFm44NNQuKkagTZ/i6IzSYIDajcI8qPyemgolM1clchSuNUu42gyRphB5MFEJDycb074p5IbqbRc8CXcN+soPkVo9PUkt72h4kMHL093rk/LhehQYteE/JBVU+Pc6bZSxQi/TSJMGSP+nOKHtv9sZBNEGlLOySbY/HpesJsxrAJnL53qZgPpBh4aTak5jib1PNOW07C2Hm1TTu/l9GcgbE9Y4P7QA==
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
    type: Opaque
